version: '3.6'
services: 
    nodejs:
        container_name: backend
        restart: always
        build: ./
        ports: 
            - "80:5000"
        links: 
            - mongo
        volumes: 
            - ./:/usr/src/nodejs
    mongo:
        image: mongo:latest
        container_name: mongodb
        ports: 
            - "27017:27017"