version: '3.6'
services: 
    nodejs:
        container_name: backend
        restart: always
        build: ./
        ports: 
            - "5000:5000"
        links: 
            - mongo
            - redis
        volumes: 
            - ./:/usr/src/nodejs
        environment: 
            REDIS_URI: redis://redis:6379
            MONGO_URI: mongodb://mongo:27017/digitaloccean-docker
    mongo:
        image: mongo:latest
        container_name: mongodb
        ports: 
            - "27017:27017"
    redis:
        image: redis
        ports: 
            - "6379:6379"